### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by FrancyMak** [OmerBenGera/SuperiorSkyblock2#104]
Java Version: 15
MC Version: Tried with last 1.16.4 and 1.16.4 build of PaperMC
SS Version: Tried with b79,b80 and 1.5.2

Files are not modified, the plug-in was started without any folder so everything is default.

```
[05:45:22 WARN]: java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(String, javax.script.Bindings)" because "com.bgsoftware.superiorskyblock.handlers.BlockValuesHandler.engine" is null
[05:45:22 WARN]:     at com.bgsoftware.superiorskyblock.handlers.BlockValuesHandler.convertValueToLevel(BlockValuesHandler.java:168)
[05:45:22 WARN]:     at com.bgsoftware.superiorskyblock.handlers.BlockValuesHandler.convertValuesToLevels(BlockValuesHandler.java:230)
[05:45:22 WARN]:     at com.bgsoftware.superiorskyblock.handlers.BlockValuesHandler.loadData(BlockValuesHandler.java:42)
[05:45:22 WARN]:     at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:325)
[05:45:22 WARN]:     at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:163)
[05:45:22 WARN]:     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[05:45:22 WARN]:     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[05:45:22 WARN]:     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[05:45:22 WARN]:     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[05:45:22 WARN]:     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[05:45:22 WARN]:     at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:466)
[05:45:22 WARN]:     at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:241)
[05:45:22 WARN]:     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:941)
[05:45:22 WARN]:     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175)
[05:45:22 WARN]:     at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by OmerBenGera** [comment]
The javascript engine is missing. Nothing to do with the plugin, but with the machine your server is running on. You can find solutions on google for that.
