### ISSUE TITLE
SlimeWorldManager and SuperiorSkyblock2

### ISSUE THREAD

**Issue by SwagPancakes** [OmerBenGera/SuperiorSkyblock2#106]
Tuinity 1.16.5 Latest
Java 11

[11:42:44] [Server thread/INFO]: [SuperiorSkyblock2] ################################################
[11:42:44] [Server thread/INFO]: [SuperiorSkyblock2] ##                                            ##
[11:42:44] [Server thread/INFO]: [SuperiorSkyblock2] ## An error occured while loading the plugin! ##
[11:42:44] [Server thread/INFO]: [SuperiorSkyblock2] ##                                            ##
[11:42:44] [Server thread/INFO]: [SuperiorSkyblock2] ################################################
[11:42:44] [Server thread/INFO]: [SuperiorSkyblock2] 
[11:42:44] [Server thread/INFO]: [SuperiorSkyblock2] Error:
[11:42:44] [Server thread/INFO]: [SuperiorSkyblock2] The spawn location is in invalid world.
[11:42:44] [Server thread/INFO]: [SuperiorSkyblock2] 
[11:42:44] [Server thread/INFO]: [SuperiorSkyblock2] StackTrace:
[11:42:44] [Server thread/INFO]: [SuperiorSkyblock2] 	at com.bgsoftware.superiorskyblock.handlers.GridHandler.updateSpawn(GridHandler.java:98)

[11:42:44] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)

[11:42:44] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)

[11:42:44] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:947)

[11:42:44] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175)

[11:42:44] [Server thread/INFO]: [SuperiorSkyblock2] 	at java.base/java.lang.Thread.run(Thread.java:834)

[11:42:44] [Server thread/INFO]: [SuperiorSkyblock2] 
[11:42:44] [Server thread/INFO]: [SuperiorSkyblock2] ################################################

How do I solve this issue?

**Comment by BingYanchi** [comment]
Your problem is not a bug, but the spawn location you set in config.yml does not exist.

The default world is SuperiorSkyblock and you need to modify it because the teleporter is detected before the world is created.

**Comment by OmerBenGera** [comment]
Do you have your spawn location in a slime world?

**Comment by SwagPancakes** [comment]
nvm I solved it it was FastAsyncWorldEdit and Idk why but FastAsyncWorldedit doesn't cooperate with advancedslimeworldmanager or slimeworldmanager

**Comment by Aeris1One** [comment]
Well, just installed Spigot or Paper, installed (Advanced-)SWM, SSB and SSB-SWM addon. At very first start (so only server.jar, eula.txt and plugins/ in server files) I have the exact same error

I tried : 
- Spigot 1.8.8 with SMW 2.2.1
- Spigot 1.12.2 with SMW 2.2.1
- Paper 1.16.5 with Advanced-SMW 2.6.1
All of those tests with SSB 1.7.0 and SSB-SMW 1.0.1

Full logs for Spigot 1.8.8 (all of tests looked quite the same)
https://paste.aeris-one.fr/?1fd72c68ee38f2de#27fwSm8k6n67Hpq7JXkyJ1Ky4WxKUGkhoc1A88ggqsQy

**Comment by OmerBenGera** [comment]
> Well, just installed Spigot or Paper, installed (Advanced-)SWM, SSB and SSB-SWM addon. At very first start (so only server.jar, eula.txt and plugins/ in server files) I have the exact same error
> 
> I tried :
> 
> * Spigot 1.8.8 with SMW 2.2.1
> * Spigot 1.12.2 with SMW 2.2.1
> * Paper 1.16.5 with Advanced-SMW 2.6.1
>   All of those tests with SSB 1.7.0 and SSB-SMW 1.0.1
> 
> Full logs for Spigot 1.8.8 (all of tests looked quite the same)
> https://paste.aeris-one.fr/?1fd72c68ee38f2de#27fwSm8k6n67Hpq7JXkyJ1Ky4WxKUGkhoc1A88ggqsQy

Read the solution above.

**Comment by Aeris1One** [comment]
Well, solution is to uninstall FAWE, and i don't have FAWE installed

**Comment by OmerBenGera** [comment]
> Well, solution is to uninstall FAWE, and i don't have FAWE installed

Open a new issue then and give qny information you have that may help fixing your bug :)
