### ISSUE TITLE
Errors related to MissionsHandler (Causing our Island Missions GUI to not open)

### ISSUE THREAD

**Issue by Skizzles** [OmerBenGera/SuperiorSkyblock2#129]
**Minecraft's Version** 1.16.5

**Plugin's Version**: SSB-b101

**Describe the bug** Errors being thrown when trying to open group missions GUI

**To Reproduce**
Updated to b101 and issue appeared, seems to be related to a handler.

**Additional information**
`[03:30:08 ERROR]: Could not pass event EntityDeathEvent to SuperiorSkyblock2 v1.5.2-DEVb101
java.lang.NullPointerException: mission parameter cannot be null.
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[patched_1.16.5.jar:git-Purpur-1001]
        at com.bgsoftware.superiorskyblock.handlers.MissionsHandler.hasCompleted(MissionsHandler.java:145) ~[?:?]
        at com.bgsoftware.superiorskyblock.handlers.MissionsHandler.lambda$hasAllRequiredMissions$4(MissionsHandler.java:212) ~[?:?]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:533) ~[?:?]
        at com.bgsoftware.superiorskyblock.handlers.MissionsHandler.hasAllRequiredMissions(MissionsHandler.java:211) ~[?:?]
        at com.bgsoftware.superiorskyblock.handlers.MissionsHandler.canCompleteNoProgress(MissionsHandler.java:203) ~[?:?]
        at com.bgsoftware.superiorskyblock.missions.KillsMissions.onEntityKill(KillsMissions.java:183) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor668.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1001]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1001]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1001]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-1001]
        at com.bgsoftware.wildstacker.listeners.EntitiesListener.lambda$null$4(EntitiesListener.java:423) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Purpur-1001]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1001]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1376) ~[patched_1.16.5.jar:git-Purpur-1001]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:389) ~[patched_1.16.5.jar:git-Purpur-1001]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1289) ~[patched_1.16.5.jar:git-Purpur-1001]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1015) ~[patched_1.16.5.jar:git-Purpur-1001]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Purpur-1001]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by OmerBenGera** [comment]
This seems to occur when you have an invalid required mission in your mission.
I will fix it on my end as well

**Comment by OmerBenGera** [comment]
Check out build 102, it should fix the error.

**Comment by Skizzles** [comment]
The errors seem to be gone. Should be good
