### ISSUE TITLE
allow-nether: true causes SS2 to complain about world already being loaded

### ISSUE THREAD

**Issue by MedicOP** [OmerBenGera/SuperiorSkyblock2#18]
I removed all world management plugins like Multiverse but SS2 keeps complaining that the world "skyblock_nether" is already loaded on startup.

My default world is called 'skyblock' and my island world is called 'sb'.

I have the generator for 'skyblock_nether' set in bukkit.yml to be an empty world already, so this warning is useless.

I had to disable `allow-nether` to fix it, but this causes nether portals to no longer work

This was working fine before updating to the latest dev build. Please revert this change.

**Comment by OmerBenGera** [comment]
It works just fine for me.
Show me your config please by uploading it to pastebin

**Comment by MedicOP** [comment]
How can it possibly work fine? When you set allow-nether to true in server.properties, it loads the world immediately on startup before loading any plugins.

**Comment by OmerBenGera** [comment]
> 
> 
> How can it possibly work fine? When you set allow-nether to true in server.properties, it loads the world immediately on startup before loading any plugins.
> 
> Then this code runs and shuts down the server
> 
> ```
> if(Bukkit.getWorld(worldName) != null){
>     throw new RuntimeException("The world " + worldName + " is already loaded. This can occur by one of the following reasons:\n" +
>             "- Another plugin loaded it manually before SuperiorSkyblock.\n" +
>             "- Your level-name property in server.properties is set to " + worldName + ".");
> }```
> ```

No... The server will only load the default worlds (aka world, world_nether and world_the_end). and SSB's custom worlds will not be loaded by it until SSB will load it.
My guess is that you configured your nether world to be the default world, which is not possible and that what causes the issue. However, you have yet to give me the error that you receive or your config, so I can only assume things without actually knowing if they are correct or not.

**Comment by MedicOP** [comment]
```
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] ################################################
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] ##                                            ##
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] ## An error occured while loading the plugin! ##
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] ##                                            ##
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] ################################################
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] 
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] Error:
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] The world skyblock_nether is already loaded. This can occur by one of the following reasons:
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] - Another plugin loaded it manually before SuperiorSkyblock.
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] - Your level-name property in server.properties is set to skyblock_nether.
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] 
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] StackTrace:
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464)
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239)
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:931)
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173)
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] 	at java.lang.Thread.run(Thread.java:748)
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] 
[08-01-2021 14:25:15] [Server thread/INFO]: [SuperiorSkyblock2] ################################################```

**Comment by MedicOP** [comment]
> No... The server will only load the default worlds (aka world, world_nether and world_the_end). and SSB's custom worlds will not be loaded by it until SSB will load it.

Yes, when you set `allow-nether` to true in server.properties, it is one of the default worlds..

If you don't set allow-nether to true in server.properties, then nether portals don't work. You told me yourself to set allow-nether to true 2 months ago in Discord.

**Comment by MedicOP** [comment]
config.yml https://pastebin.com/raw/UHrc9XBh

**Comment by MedicOP** [comment]
In server.properties:
```
level-name=skyblock
allow-nether=true```

**Comment by MedicOP** [comment]
I don't understand what you expect people to do? You expect them to set allow-nether to true and then ALSO have a SS2 custom nether world?? Why would I want to have 2 different nether worlds? Obviously I want SS2 to use the default nether world..

Again, I have been using this setup for 2 months with no issues until I updated to the latest dev build.

**Comment by MedicOP** [comment]
If people want to have both nether and end, you apparently want them to have 6 worlds:
- world
- world_nether (useless)
- world_the_end (useless)
- sb
- sb_nether
- sb_the_end

**Comment by OmerBenGera** [comment]
You can't have your island worlds as default worlds, that's it.
The default nether & end will be generated and there's nothing to do with that and it's really not related to the plugin.
I am closing this

**Comment by MedicOP** [comment]
How can I not when I have been doing exactly that for 2 months already rofl?

I've literally showed you above how to do that. It only broke 6 days ago when you added this check. What's so hard about just removing it?

**Comment by MedicOP** [comment]
All you have to do is set the generator in bukkit.yml to be an empty world.

You're telling me people should have 6 different worlds just to have nether and end islands roflmao

**Comment by MedicOP** [comment]
You are stubborn

**Comment by MedicOP** [comment]
It's no wonder PayPal and spigot banned you lmao

**Comment by MedicOP** [comment]
have to fight 2 hours every single time i want a tiny bug fixed

**Comment by MedicOP** [comment]
bans me from discord for trying to get a bug fixed

again if i hadn't argued on discord for 2 fucking hours last time, wildstacker would still have a memory leak lol

accept that there are people out there who know more about developing than you do

i mean i literally just gave you another solution to a bug EntityPortalEnterEvent 5 minutes ago

that's like the 10th bug i've gotten fixed

my reward? getting banned

**Comment by OmerBenGera** [comment]
I locked this issue due to MedicOP spamming it with comments.
You weren't banned from the discord, only kicked as you spammed the channel instead of listening for once.

**Comment by OmerBenGera** [comment]
I am fixing your bug, I kicked you because you spammed and haven't stopped.
Cancel your dispute as you bought the plugin on October and you had no issues until now.
Also, if you have read the announcements, you'd notice that the plugin is provided now "as is", which means I don't guarantee any updates.
