### ISSUE TITLE
Error with /is biome

### ISSUE THREAD

**Issue by Skizzles** [OmerBenGera/SuperiorSkyblock2#44]
1.16.5 Yatopia
SuperiorSkyblock-b46

Seems like an issue getting the biome in the chunk?
https://pastebin.com/haPxczGj

**Comment by Skizzles** [comment]
[06:27:47 WARN]: java.lang.RuntimeException: Error while receiving biome bases of chunk (1049,861).
[06:27:47 WARN]:        at com.bgsoftware.superiorskyblock.nms.NMSBlocks_v1_16_R3.lambda$setChunkBiome$8(NMSBlocks_v1_16_R3.java:517)
[06:27:47 WARN]:        at com.bgsoftware.superiorskyblock.nms.NMSBlocks_v1_16_R3.runActionOnChunk(NMSBlocks_v1_16_R3.java:549)
[06:27:47 WARN]:        at com.bgsoftware.superiorskyblock.nms.NMSBlocks_v1_16_R3.runActionOnChunk(NMSBlocks_v1_16_R3.java:539)
[06:27:47 WARN]:        at com.bgsoftware.superiorskyblock.nms.NMSBlocks_v1_16_R3.setChunkBiome(NMSBlocks_v1_16_R3.java:513)
[06:27:47 WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.lambda$setBiome$61(SIsland.java:1376)
[06:27:47 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
[06:27:47 WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.setBiome(SIsland.java:1375)
[06:27:47 WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.setBiome(SIsland.java:1364)
[06:27:47 WARN]:        at com.bgsoftware.superiorskyblock.handlers.GridHandler.lambda$createIsland$3(GridHandler.java:166)
[06:27:47 WARN]:        at com.bgsoftware.superiorskyblock.schematics.SuperiorSchematic.lambda$pasteSchematic$1(SuperiorSchematic.java:200)
[06:27:47 WARN]:        at com.bgsoftware.superiorskyblock.utils.blocks.BlockChangeTask.lambda$submitUpdate$4(BlockChangeTask.java:74)
[06:27:47 WARN]:        at com.bgsoftware.superiorskyblock.utils.chunks.ChunksProvider.lambda$finishLoad$2(ChunksProvider.java:88)
[06:27:47 WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[06:27:47 WARN]:        at com.bgsoftware.superiorskyblock.utils.chunks.ChunksProvider.finishLoad(ChunksProvider.java:88)
[06:27:47 WARN]:        at com.bgsoftware.superiorskyblock.utils.chunks.ChunksProvider.lambda$null$0(ChunksProvider.java:80)
[06:27:47 WARN]:        at com.bgsoftware.superiorskyblock.hooks.AsyncProvider_Paper.lambda$loadChunk$0(AsyncProvider_Paper.java:16)
[06:27:47 WARN]:        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
[06:27:47 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
[06:27:47 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
[06:27:47 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
[06:27:47 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
[06:27:47 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[06:27:47 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.execute(IAsyncTaskHandler.java:89)
[06:27:47 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
[06:27:47 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1069)
[06:27:47 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
[06:27:47 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
[06:27:47 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
[06:27:47 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[06:27:47 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[06:27:47 WARN]:        at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:1204)
[06:27:47 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[06:27:47 WARN]:        at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1218)
[06:27:47 WARN]:        at net.minecraft.server.v1_16_R3.ChunkProviderServer.runTasks(ChunkProviderServer.java:805)
[06:27:47 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1220)
[06:27:47 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1203)
[06:27:47 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[06:27:47 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1179)
[06:27:47 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1023)
[06:27:47 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175)
[06:27:47 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by OmerBenGera** [comment]
Hey, what version exactly of Yatopia are you using?

**Comment by Skizzles** [comment]
b12, I see they changed some stuff with biome compatibility in b13. However I am switching off Yatopia to Purpur because of the lack of regard for stuff like this.

**Comment by OmerBenGera** [comment]
> 
> 
> b12, I see they changed some stuff with biome compatibility in b13. However I am switching off Yatopia to Purpur because of the lack of regard for stuff like this.

I've just tried it with b13 and it seemed to work for me, mind checking it as well?

**Comment by Skizzles** [comment]
> > b12, I see they changed some stuff with biome compatibility in b13. However I am switching off Yatopia to Purpur because of the lack of regard for stuff like this.
> 
> I've just tried it with b13 and it seemed to work for me, mind checking it as well?

Ye dude its fixed with B13. Sigh. I will close this out.
