### ISSUE TITLE
 SSB-SlimeWorldManager cannot delete a player island

### ISSUE THREAD

**Issue by bithuc** [OmerBenGera/SuperiorSkyblock2#54]
**I hooked the plugin to the addon ssb swm.
When using /is disband, an error will occur.
And I cannot recreate the island**

`[17:10:58 INFO]: Hykira issued server command: /is admin disband Hykira
> 
[17:10:58 WARN]: java.lang.NullPointerException
[17:10:58 WARN]:  at com.bgsoftware.ssbslimeworldmanager.SlimeUtils.deleteWorld(SlimeUtils.java:97)
[17:10:58 WARN]:  at com.bgsoftware.ssbslimeworldmanager.SSBSlimeWorldManager.lambda$onIslandDelete$0(SSBSlimeWorldManager.java:39)
[17:10:58 WARN]:  at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[17:10:58 INFO]: [SWM World] Saving world island_42cd7952-cb78-411c-9db5-4acdbb4a3b7e_normal...
[17:10:58 INFO]: [SWM World] World island_42cd7952-cb78-411c-9db5-4acdbb4a3b7e_normal saved in 14ms.
[17:10:58 WARN]:  at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
[17:10:58 WARN]:  at com.bgsoftware.ssbslimeworldmanager.SSBSlimeWorldManager.onIslandDelete(SSBSlimeWorldManager.java:39)
[17:10:58 WARN]:  at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor54.execute(Unknown Source)
 [17:10:58 WARN]:  at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[17:10:58 WARN]:  at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[17:10:58 WARN]:  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[17:10:58 WARN]:  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[17:10:58 WARN]:  at com.bgsoftware.superiorskyblock.utils.events.EventsCaller.callIslandDisbandEvent(EventsCaller.java:118)
[17:10:58 WARN]:  at com.bgsoftware.superiorskyblock.commands.admin.CmdAdminDisband.execute(CmdAdminDisband.java:64)
[17:10:58 WARN]:  at com.bgsoftware.superiorskyblock.commands.IAdminIslandCommand.execute(IAdminIslandCommand.java:21)
[17:10:58 WARN]:  at com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.execute(ISuperiorCommand.java:13)
[17:10:58 WARN]:  at com.bgsoftware.superiorskyblock.commands.CmdAdmin.execute(CmdAdmin.java:166)
[17:10:58 WARN]:  at com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.execute(ISuperiorCommand.java:13)
[17:10:58 WARN]:  at com.bgsoftware.superiorskyblock.handlers.CommandsHandler$PluginCommand.execute(CommandsHandler.java:336)
[17:10:58 WARN]:  at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[17:10:58 WARN]:  at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[17:10:58 WARN]:  at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492)
[17:10:58 WARN]:  at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297)
[17:10:58 WARN]:  at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:10:58 WARN]:  at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[17:10:58 WARN]:  at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[17:10:58 WARN]:  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 [17:10:58 WARN]:  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 [17:10:58 WARN]:  at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[17:10:58 WARN]:  at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[17:10:58 WARN]:  at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[17:10:58 WARN]:  at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[17:10:58 WARN]:  at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[17:10:58 WARN]:  at java.lang.Thread.run(Thread.java:748)
[17:10:58 WARN]: java.lang.NullPointerException
[17:10:58 WARN]:  at com.bgsoftware.ssbslimeworldmanager.SlimeUtils.deleteWorld(SlimeUtils.java:97)
[17:10:58 WARN]:  at com.bgsoftware.ssbslimeworldmanager.SSBSlimeWorldManager.lambda$onIslandDelete$0(SSBSlimeWorldManager.java:39)
[17:10:58 WARN]:  at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[17:10:58 WARN]:  at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
[17:10:58 WARN]:  at com.bgsoftware.ssbslimeworldmanager.SSBSlimeWorldManager.onIslandDelete(SSBSlimeWorldManager.java:39)
[17:10:58 WARN]:  at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor54.execute(Unknown Source)
[17:10:58 WARN]:  at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[17:10:58 WARN]:  at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[17:10:58 WARN]:  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[17:10:58 WARN]:  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[17:10:58 WARN]:  at com.bgsoftware.superiorskyblock.utils.events.EventsCaller.callIslandDisbandEvent(EventsCaller.java:118)
[17:10:58 WARN]:  at com.bgsoftware.superiorskyblock.commands.admin.CmdAdminDisband.execute(CmdAdminDisband.java:64)
[17:10:58 WARN]:  at com.bgsoftware.superiorskyblock.commands.IAdminIslandCommand.execute(IAdminIslandCommand.java:21)
[17:10:58 WARN]:  at com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.execute(ISuperiorCommand.java:13)
[17:10:58 WARN]:  at com.bgsoftware.superiorskyblock.commands.CmdAdmin.execute(CmdAdmin.java:166)
[17:10:58 WARN]:  at com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.execute(ISuperiorCommand.java:13)
[17:10:58 WARN]:  at com.bgsoftware.superiorskyblock.handlers.CommandsHandler$PluginCommand.execute(CommandsHandler.java:336)
[17:10:58 WARN]:  at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[17:10:58 WARN]:  at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[17:10:58 WARN]:  at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492)
[17:10:58 WARN]:  at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297)
[17:10:58 WARN]:  at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:10:58 WARN]:  at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[17:10:58 WARN]:  at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[17:10:58 WARN]:  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:10:58 WARN]:  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:10:58 WARN]:  at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[17:10:58 WARN]:  at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[17:10:58 WARN]:  at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[17:10:58 WARN]:  at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[17:10:58 WARN]:  at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[17:10:58 
WARN]:  at java.lang.Thread.run(Thread.java:748)
> [17:10:58 INFO]: [SWM] Loading world island_42cd7952-cb78-411c-9db5-4acdbb4a3b7e_normal.
> 

        at com.bgsoftware.ssbslimeworldmanager.SlimeUtils.loadAndGetWorld(SlimeUtils.java:47) ~[?:?]
at com.bgsoftware.ssbslimeworldmanager.SSBWorldManager$SlimeWorldsProvider.getIslandsWorld(SSBWorldManager.java:27) ~[?:?]
at com.bgsoftware.superiorskyblock.handlers.ProvidersHandler.getIslandsWorld(ProvidersHandler.java:313) ~[?:?]
at com.bgsoftware.superiorskyblock.handlers.GridHandler.getIslandsWorld(GridHandler.java:343) ~[?:?]
at com.bgsoftware.superiorskyblock.island.SIsland.getCenter(SIsland.java:648) ~[?:?]
at com.bgsoftware.superiorskyblock.utils.islands.IslandUtils.getChunkCoords(IslandUtils.java:65) ~[?:?]
at com.bgsoftware.superiorskyblock.island.SIsland.resetChunks(SIsland.java:860) ~[?:?]
at com.bgsoftware.superiorskyblock.island.SIsland.resetChunks(SIsland.java:855) ~[?:?]
at com.bgsoftware.superiorskyblock.island.SIsland.disbandIsland(SIsland.java:1146) ~[?:?]
at com.bgsoftware.superiorskyblock.commands.admin.CmdAdminDisband.execute(CmdAdminDisband.java:77) ~[?:?]
at com.bgsoftware.superiorskyblock.commands.IAdminIslandCommand.execute(IAdminIslandCommand.java:21) ~[?:?]
at com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.execute(ISuperiorCommand.java:13) ~[?:?]
at com.bgsoftware.superiorskyblock.commands.CmdAdmin.execute(CmdAdmin.java:166) ~[?:?]
at com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.execute(ISuperiorCommand.java:13) ~[?:?]
at com.bgsoftware.superiorskyblock.handlers.CommandsHandler$PluginCommand.execute(CommandsHandler.java:336) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.12.2.jar:git-Paper-1618]
... 14 more
Caused by: com.grinderwolf.swm.api.exceptions.UnknownWorldException: Unknown world island_42cd7952-cb78-411c-9db5-4acdbb4a3b7e_normal
at com.grinderwolf.swm.plugin.loaders.file.FileLoader.loadWorld(Fil
        at com.bgsoftware.ssbslimeworldmanager.SlimeUtils.loadAndGetWorld(SlimeUtils.java:51) ~[?:?]
at com.bgsoftware.ssbslimeworldmanager.SlimeUtils.loadAndGetWorld(SlimeUtils.java:47) ~[?:?]
at com.bgsoftware.ssbslimeworldmanager.SSBWorldManager$SlimeWorldsProvider.getIslandsWorld(SSBWorldManager.java:27) ~[?:?]
at com.bgsoftware.superiorskyblock.handlers.ProvidersHandler.getIslandsWorld(ProvidersHandler.java:313) ~[?:?]
at com.bgsoftware.superiorskyblock.handlers.GridHandler.getIslandsWorld(GridHandler.java:343) ~[?:?]
at com.bgsoftware.superiorskyblock.island.SIsland.getCenter(SIsland.java:648) ~[?:?]
at com.bgsoftware.superiorskyblock.utils.islands.IslandUtils.getChunkCoords(IslandUtils.java:65) ~[?:?]
at com.bgsoftware.superiorskyblock.island.SIsland.resetChunks(SIsland.java:860) ~[?:?]
at com.bgsoftware.superiorskyblock.island.SIsland.resetChunks(SIsland.java:855) ~[?:?]
at com.bgsoftware.superiorskyblock.island.SIsland.disbandIsland(SIsland.java:1146) ~[?:?]
at com.bgsoftware.superiorskyblock.commands.admin.CmdAdminDisband.execute(CmdAdminDisband.java:77) ~[?:?]
at com.bgsoftware.superiorskyblock.commands.IAdminIslandCommand.execute(IAdminIslandCommand.java:21) ~[?:?]
at com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.execute(ISuperiorCommand.java:13) ~[?:?]
at com.bgsoftware.superiorskyblock.commands.CmdAdmin.execute(CmdAdmin.java:166) ~[?:?]
at com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.execute(ISuperiorCommand.java:13) ~[?:?]
at com.bgsoftware.superiorskyblock.handlers.CommandsHandler$PluginCommand.execute(CommandsHandler.java:336) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.12.2.jar:git-Paper-1618]
... 14 more
> 
`

**Comment by bithuc** [comment]
i using ver B52 and server version 1.12.2

**Comment by bithuc** [comment]
I can't even use the command  /is disband ... I have dropped the timeout to activate the reversal

**Comment by OmerBenGera** [comment]
This has nothing to do with SSB - it's an issue with the addon.
However, it looks like you just don't have the data source set correctly or something.
Anyways, not related to SSB in any way
