### ISSUE TITLE
World generator error

### ISSUE THREAD

**Issue by TheYashe** [OmerBenGera/SuperiorSkyblock2#69]
### Running it on latest spigot 1.16.5 causes a world generation problem.

[18:43:06] [Worker-Main-8/INFO]: Preparing spawn area: 0% 
[18:43:06] [Worker-Main-17/FATAL]: Failed to schedule load callback for chunk [0, 0]
java.util.concurrent.CompletionException: java.lang.NoSuchFieldError: g
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_281]
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:1.8.0_281]
        at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) ~[?:1.8.0_281]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:1.8.0_281]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_281]
        at net.minecraft.server.v1_16_R3.ChunkTaskQueueSorter.b(SourceFile:58) ~[spigot-1.16.5.jar:3009-Spigot-73fb609-d97d918]
        at net.minecraft.server.v1_16_R3.ThreadedMailbox.e(SourceFile:94) [spigot-1.16.5.jar:3009-Spigot-73fb609-d97d918]
        at net.minecraft.server.v1_16_R3.ThreadedMailbox.a(SourceFile:137) [spigot-1.16.5.jar:3009-Spigot-73fb609-d97d918]
        at net.minecraft.server.v1_16_R3.ThreadedMailbox.run(SourceFile:105) [spigot-1.16.5.jar:3009-Spigot-73fb609-d97d918]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) [?:1.8.0_281]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_281]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_281]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_281]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NoSuchFieldError: g
        at com.bgsoftware.superiorskyblock.nms.NMSAdapter_v1_16_R3.setBiome(NMSAdapter_v1_16_R3.java:212) ~[?:?]
        at com.bgsoftware.superiorskyblock.generator.WorldGenerator.generateChunkData(WorldGenerator.java:53) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.generator.CustomChunkGenerator.buildBase(CustomChunkGenerator.java:115) ~[spigot-1.16.5.jar:3009-Spigot-73fb609-d97d918]
        at net.minecraft.server.v1_16_R3.ChunkStatus.lambda$5(ChunkStatus.java:55) ~[spigot-1.16.5.jar:3009-Spigot-73fb609-d97d918]
        at net.minecraft.server.v1_16_R3.ChunkStatus$d.doWork(ChunkStatus.java:233) ~[spigot-1.16.5.jar:3009-Spigot-73fb609-d97d918]
        at net.minecraft.server.v1_16_R3.ChunkStatus.a(ChunkStatus.java:190) ~[spigot-1.16.5.jar:3009-Spigot-73fb609-d97d918]
        at net.minecraft.server.v1_16_R3.PlayerChunkMap.lambda$26(PlayerChunkMap.java:538) ~[spigot-1.16.5.jar:3009-Spigot-73fb609-d97d918]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[spigot-1.16.5.jar:3009-Spigot-73fb609-d97d918]
        at net.minecraft.server.v1_16_R3.PlayerChunkMap.lambda$24(PlayerChunkMap.java:536) ~[spigot-1.16.5.jar:3009-Spigot-73fb609-d97d918]
        ... 12 more

**Comment by MassiveLag** [comment]
Same thing

**Comment by OmerBenGera** [comment]
Update to latest dev build, this issue was fixed a while ago
